# pyright: reportUnusedImport=false, reportArgumentType=false
"""paypal

Revision ID: 14014b3bdf47
Revises: 256c6bc206ea
Create Date: 2026-04-13 08:15:40.522392+00:00

"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa
import sqlmodel
import sqlmodel.sql.sqltypes

from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '14014b3bdf47'
down_revision: str | Sequence[str] | None = '256c6bc206ea'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    sa.Enum('COMPLETED', 'PENDING', 'FAILED', 'REFUNDED', 'CANCELED', name='transactionstatus').create(op.get_bind())
    op.create_table('paypal_transactions',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('order_id', sa.Uuid(), nullable=True),
    sa.Column('transaction_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('status', postgresql.ENUM('COMPLETED', 'PENDING', 'FAILED', 'REFUNDED', 'CANCELED', name='transactionstatus', create_type=False), nullable=False),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], name=op.f('fk_paypal_transactions_order_id_orders'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_paypal_transactions'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('paypal_transactions')
    sa.Enum('COMPLETED', 'PENDING', 'FAILED', 'REFUNDED', 'CANCELED', name='transactionstatus').drop(op.get_bind())
    # ### end Alembic commands ###
