# pyright: reportUnusedImport=false, reportArgumentType=false
"""remove max age from database

Revision ID: 1958e1fb4c80
Revises: f412b7be0963
Create Date: 2026-04-18 15:30:35.367960+00:00

"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa
import sqlmodel
import sqlmodel.sql.sqltypes



# revision identifiers, used by Alembic.
revision: str = '1958e1fb4c80'
down_revision: str | Sequence[str] | None = 'f412b7be0963'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('email_verification_tokens', 'max_age')
    op.drop_column('orders', 'max_age')
    op.drop_column('password_reset_tokens', 'max_age')
    op.drop_column('sessions', 'max_age')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sessions', sa.Column('max_age', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('password_reset_tokens', sa.Column('max_age', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('orders', sa.Column('max_age', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('email_verification_tokens', sa.Column('max_age', sa.INTEGER(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
