# pyright: reportUnusedImport=false, reportArgumentType=false
"""orders

Revision ID: 256c6bc206ea
Revises: a5019bf5cb08
Create Date: 2026-04-12 15:51:40.582247+00:00

"""
from collections.abc import Sequence

import sqlalchemy as sa
import sqlmodel
import sqlmodel.sql.sqltypes
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '256c6bc206ea'
down_revision: str | Sequence[str] | None = 'a5019bf5cb08'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    sa.Enum('Australian_dollar', 'Brazilian_real', 'Canadian_dollar', 'Chinese_Renmenbi', 'Czech_koruna', 'Danish_krone', 'Euro', 'Hong_Kong_dollar', 'Malaysian_ringgit', 'Mexican_peso', 'New_Zealand_dollar', 'Norwegian_krone', 'Philippine_peso', 'Polish_złoty', 'Pound_sterling', 'Russian_ruble', 'Singapore_dollar', 'Swedish_krona', 'Swiss_franc', 'Thai_baht', 'United_States_dollar', name='currency').create(op.get_bind())
    op.create_table('orders',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('currency', postgresql.ENUM('Australian_dollar', 'Brazilian_real', 'Canadian_dollar', 'Chinese_Renmenbi', 'Czech_koruna', 'Danish_krone', 'Euro', 'Hong_Kong_dollar', 'Malaysian_ringgit', 'Mexican_peso', 'New_Zealand_dollar', 'Norwegian_krone', 'Philippine_peso', 'Polish_złoty', 'Pound_sterling', 'Russian_ruble', 'Singapore_dollar', 'Swedish_krona', 'Swiss_franc', 'Thai_baht', 'United_States_dollar', name='currency', create_type=False), nullable=False),
    sa.Column('ray_id', sa.Uuid(), nullable=False),
    sa.Column('price', sa.Float(), nullable=False),
    sa.Column('max_age', sa.Integer(), nullable=False),
    sa.Column('paid', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_orders_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_orders')),
    sa.UniqueConstraint('user_id', 'ray_id', name=op.f('uq_orders_user_id'))
    )
    op.create_table('orderproductlink',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('count', sa.Integer(), nullable=False),
    sa.Column('price', sa.Float(), nullable=False),
    sa.Column('order_id', sa.Uuid(), nullable=False),
    sa.Column('product_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], name=op.f('fk_orderproductlink_order_id_orders')),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], name=op.f('fk_orderproductlink_product_id_products')),
    sa.PrimaryKeyConstraint('id', 'order_id', 'product_id', name=op.f('pk_orderproductlink'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('orderproductlink')
    op.drop_table('orders')
    sa.Enum('Australian_dollar', 'Brazilian_real', 'Canadian_dollar', 'Chinese_Renmenbi', 'Czech_koruna', 'Danish_krone', 'Euro', 'Hong_Kong_dollar', 'Malaysian_ringgit', 'Mexican_peso', 'New_Zealand_dollar', 'Norwegian_krone', 'Philippine_peso', 'Polish_złoty', 'Pound_sterling', 'Russian_ruble', 'Singapore_dollar', 'Swedish_krona', 'Swiss_franc', 'Thai_baht', 'United_States_dollar', name='currency').drop(op.get_bind())
    # ### end Alembic commands ###
