# pyright: reportUnusedImport=false, reportArgumentType=false
"""generalize transaction logic

Revision ID: 5ff8855d0322
Revises: 14014b3bdf47
Create Date: 2026-04-13 18:16:26.707971+00:00

"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa
import sqlmodel
import sqlmodel.sql.sqltypes

from alembic_postgresql_enum import TableReference
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '5ff8855d0322'
down_revision: str | Sequence[str] | None = '14014b3bdf47'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    sa.Enum('PAYPAL', name='paymentprovider').create(op.get_bind())
    op.create_table('transactions',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('order_id', sa.Uuid(), nullable=True),
    sa.Column('user_id', sa.Uuid(), nullable=True),
    sa.Column('provider', postgresql.ENUM('PAYPAL', name='paymentprovider', create_type=False), nullable=False),
    sa.Column('transaction_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('price', sa.Float(), nullable=False),
    sa.Column('status', postgresql.ENUM('COMPLETED', 'PENDING', 'AUTHORIZED', 'FAILED', 'REFUNDED', 'CANCELED', name='transactionstatus', create_type=False), nullable=False),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], name=op.f('fk_transactions_order_id_orders')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_transactions_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_transactions')),
    sa.UniqueConstraint('transaction_id', 'provider', name=op.f('uq_transactions_transaction_id'))
    )
    op.drop_table('paypal_transactions')
    op.sync_enum_values(
        enum_schema='public',
        enum_name='transactionstatus',
        new_values=['COMPLETED', 'PENDING', 'AUTHORIZED', 'FAILED', 'REFUNDED', 'CANCELED'],
        affected_columns=[TableReference(table_schema='public', table_name='transactions', column_name='status')],
        enum_values_to_rename=[],
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.sync_enum_values(
        enum_schema='public',
        enum_name='transactionstatus',
        new_values=['COMPLETED', 'PENDING', 'FAILED', 'REFUNDED', 'CANCELED'],
        affected_columns=[TableReference(table_schema='public', table_name='transactions', column_name='status')],
        enum_values_to_rename=[],
    )
    op.create_table('paypal_transactions',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('order_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('transaction_id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('amount', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('status', postgresql.ENUM('COMPLETED', 'PENDING', 'FAILED', 'REFUNDED', 'CANCELED', name='transactionstatus', create_type=False), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], name=op.f('fk_paypal_transactions_order_id_orders'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_paypal_transactions'))
    )
    op.drop_table('transactions')
    sa.Enum('PAYPAL', name='paymentprovider').drop(op.get_bind())
    # ### end Alembic commands ###
