# pyright: reportUnusedImport=false, reportArgumentType=false
"""reset token hash

Revision ID: 6b552e8b552f
Revises: fe2da2ca6dbc
Create Date: 2026-04-18 14:45:47.999328+00:00

"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa
import sqlmodel
import sqlmodel.sql.sqltypes



# revision identifiers, used by Alembic.
revision: str = '6b552e8b552f'
down_revision: str | Sequence[str] | None = 'fe2da2ca6dbc'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('email_verification_tokens', sa.Column('token_hash', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    op.drop_constraint(op.f('uq_email_verification_tokens_token'), 'email_verification_tokens', type_='unique')
    op.drop_column('email_verification_tokens', 'token')
    op.add_column('password_reset_tokens', sa.Column('token_hash', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    op.drop_constraint(op.f('uq_password_reset_tokens_token'), 'password_reset_tokens', type_='unique')
    op.drop_column('password_reset_tokens', 'token')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('password_reset_tokens', sa.Column('token', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.create_unique_constraint(op.f('uq_password_reset_tokens_token'), 'password_reset_tokens', ['token'], postgresql_nulls_not_distinct=False)
    op.drop_column('password_reset_tokens', 'token_hash')
    op.add_column('email_verification_tokens', sa.Column('token', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.create_unique_constraint(op.f('uq_email_verification_tokens_token'), 'email_verification_tokens', ['token'], postgresql_nulls_not_distinct=False)
    op.drop_column('email_verification_tokens', 'token_hash')
    # ### end Alembic commands ###
