# pyright: reportUnusedImport=false, reportArgumentType=false
"""paypal authorization id field

Revision ID: 72cb7bbf67ed
Revises: 5ff8855d0322
Create Date: 2026-04-14 09:49:42.571070+00:00

"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa
import sqlmodel
import sqlmodel.sql.sqltypes



# revision identifiers, used by Alembic.
revision: str = '72cb7bbf67ed'
down_revision: str | Sequence[str] | None = '5ff8855d0322'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transactions', sa.Column('authorization_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('transactions', 'authorization_id')
    # ### end Alembic commands ###
