# pyright: reportUnusedImport=false, reportArgumentType=false
"""ip and useragent

Revision ID: 73acc71a3790
Revises: 72cb7bbf67ed
Create Date: 2026-04-17 20:48:04.753589+00:00

"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa
import sqlmodel
import sqlmodel.sql.sqltypes



# revision identifiers, used by Alembic.
revision: str = '73acc71a3790'
down_revision: str | Sequence[str] | None = '72cb7bbf67ed'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sessions', sa.Column('ip_address', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('sessions', sa.Column('user_agent', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sessions', 'user_agent')
    op.drop_column('sessions', 'ip_address')
    # ### end Alembic commands ###
