# pyright: reportUnusedImport=false, reportArgumentType=false
"""user_model_update

Revision ID: 9a6b83c4025f
Revises: e2f5707f9f22
Create Date: 2026-03-27 10:36:08.367456+00:00

"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa
import sqlmodel
import sqlmodel.sql.sqltypes

from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '9a6b83c4025f'
down_revision: str | Sequence[str] | None = 'e2f5707f9f22'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sessions', sa.Column('max_age', sa.Integer(), nullable=False))
    op.drop_column('sessions', 'expires_at')
    op.create_unique_constraint(None, 'users', ['email'])
    op.create_unique_constraint(None, 'users', ['username'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='unique')
    op.drop_constraint(None, 'users', type_='unique')
    op.add_column('sessions', sa.Column('expires_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False))
    op.drop_column('sessions', 'max_age')
    # ### end Alembic commands ###
