# pyright: reportUnusedImport=false, reportArgumentType=false
"""regen constraints

Revision ID: a5019bf5cb08
Revises: da8da6bb3874
Create Date: 2026-03-28 16:02:19.830027+00:00

"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa
import sqlmodel
import sqlmodel.sql.sqltypes



# revision identifiers, used by Alembic.
revision: str = 'a5019bf5cb08'
down_revision: str | Sequence[str] | None = 'da8da6bb3874'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('sessions_token_key'), 'sessions', type_='unique')
    op.create_unique_constraint(op.f('uq_sessions_token'), 'sessions', ['token'])
    op.drop_constraint(op.f('users_email_key'), 'users', type_='unique')
    op.drop_constraint(op.f('users_username_key'), 'users', type_='unique')
    op.create_unique_constraint(op.f('uq_users_email'), 'users', ['email'])
    op.create_unique_constraint(op.f('uq_users_username'), 'users', ['username'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('uq_users_username'), 'users', type_='unique')
    op.drop_constraint(op.f('uq_users_email'), 'users', type_='unique')
    op.create_unique_constraint(op.f('users_username_key'), 'users', ['username'], postgresql_nulls_not_distinct=False)
    op.create_unique_constraint(op.f('users_email_key'), 'users', ['email'], postgresql_nulls_not_distinct=False)
    op.drop_constraint(op.f('uq_sessions_token'), 'sessions', type_='unique')
    op.create_unique_constraint(op.f('sessions_token_key'), 'sessions', ['token'], postgresql_nulls_not_distinct=False)
    # ### end Alembic commands ###
