# pyright: reportUnusedImport=false, reportArgumentType=false
"""cache location in redis

Revision ID: f412b7be0963
Revises: 6b552e8b552f
Create Date: 2026-04-18 15:29:58.118860+00:00

"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa
import sqlmodel
import sqlmodel.sql.sqltypes



# revision identifiers, used by Alembic.
revision: str = 'f412b7be0963'
down_revision: str | Sequence[str] | None = '6b552e8b552f'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sessions', sa.Column('location', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sessions', 'location')
    # ### end Alembic commands ###
