# pyright: reportUnusedImport=false, reportArgumentType=false
"""cascade

Revision ID: ff22f393231f
Revises: 698be80e52f6
Create Date: 2026-03-28 11:34:53.159831+00:00

"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa
import sqlmodel
import sqlmodel.sql.sqltypes



# revision identifiers, used by Alembic.
revision: str = 'ff22f393231f'
down_revision: str | Sequence[str] | None = '698be80e52f6'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('products_catid_fkey'), 'products', type_='foreignkey')
    op.create_foreign_key(op.f('products_catid_fkey'), 'products', 'categories', ['catid'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('sessions_user_id_fkey'), 'sessions', type_='foreignkey')
    op.create_foreign_key(op.f('sessions_user_id_fkey'), 'sessions', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('sessions_user_id_fkey'), 'sessions', type_='foreignkey')
    op.create_foreign_key(op.f('sessions_user_id_fkey'), 'sessions', 'users', ['user_id'], ['id'])
    op.drop_constraint(op.f('products_catid_fkey'), 'products', type_='foreignkey')
    op.create_foreign_key(op.f('products_catid_fkey'), 'products', 'categories', ['catid'], ['id'])
    # ### end Alembic commands ###
