services:
  db:
    image: postgres:18
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      PGDATA: /var/lib/postgresql/data
    volumes:
      - db_data:/var/lib/postgresql/data
  web:
    build: ./web
    ports:
      - 3000:3000
    environment:
      - API_URL=${API_URL}
      - SIGNING_SECRET=${SIGNING_SECRET}
  api:
    build: ./api
    environment:
      - POSTGRES_URL=${POSTGRES_URL}
      - EXE_MODE=${EXE_MODE}

volumes:
  db_data:
